### ISSUE TITLE
Please use `cm³` instead of `cm^3`

### ISSUE THREAD

**Issue by kseistrup** [spirometaxas/periodic-table-cli-py#9]
The TUI is pretty, but `cm^3` looks just wrong. Fortunately, it's easy to correct:

```sh
sed -i 's/cm^3/cm³/g' data.json
```

**Comment by spirometaxas** [comment]
Thanks for the suggestion!  This change has been added to version [2.1.1](https://github.com/spirometaxas/periodic-table-cli-py/releases/tag/v2.1.1).  Let me know if you see any issues.

**Comment by kseistrup** [comment]
Looks perfect to me. :+1:
